# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c781faac6f2e81ba270a2ebccd7f27e5fc6e380dcc37ba12ca40f10f5a1608e04c4cb89546029ec42da593d8fd73036001db79c96107fcf6445192404813856

test:
  secret_key_base: 6a142e1b47cae86c3812796d55691df5bf7d5b0044347d0c42164213ad2910850036f1e90fca0f765198e723ca464d06f77089cfb9ee71968fb0cd5e9b0c0a8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
